export const ac = {
  // This is the Acholi dialect, for Ugandan users.
  appTitle1: "Pareto",
  email: "Email ni",
  login: "donyi",
  logout: "Kat woko",
  loggingIn: "Ti donyo...",
  signup: "cone kan",
  signingUp: "Ti cone kumbedi",
  password: "Password ni",
  oldPassword: "Password ni macon",
  newPassword: "Password ni manyen",
  confirm: "Mogi Password",
  confirmationCode: "Confirmation Code",
  checkEmail: "Tim ber iceri i email ni ki ibino iye code ma ki cwali.",
  resetPassword: "logi Password",
  lowerArena: "The Arena",
  // landing copy, this is what is visible on the first page.
  firstLanding: `Pwony coyo program mi computer luremi ki lupwonyi kacel.`,
  secondLanding: `Yubbe maber ki pyem ki luremi ka cubu cwinyi no iti i kwan mi lubu tic ma cwinyi maru.`,
  thirdLanding:
    "No ngec mi tiyu ki jemi mapatpat make yubu plogram mi computer, yubi product ni macel ma kabeddu i portfolio ni, ki bene kwan pwony ma pire tek tutwal i tic mi computer science irom karu peny mi ikom computer maber.",
  // profile
  saving: "Ti gwoko...",
  saveProfile: "Gwok Profile ni",
  firstName: "nying me dini",
  lastName: "nying me acholi",
  github: "nyinyi ma itiyo kere i GitHub",
  city: "City",
  country: "lobo ni",
  phone: "namba cim",
  // interface
  createNewUser: "cone ma nyen",
  userDirectory: "User Directory",
  matchUsers: "Match Users",
  mentorshipList: "Nen Mentorships ki Sprint Templates",
  sandbox: "Sandbok",
  promoteUser: "Upgrade User",
  basicTraining: "Full-Stack JS",
  technicalTraining: "Dev Onboarding",
  findingWork: "nyiyu tic",
  cityByCity: "City Guides",
  training: "Onboarding",
  product: "Yubi Product ni",
  interviewing: "Pwony Interviews",
  arena: "The Arena",
  arenaSprints: "Arena Sprints",
  mentorship: "Mentorships",
  achievement: "Achievement",
  viewDailyAchievements: "",
  neuroProfile: "Neuro Athletic Profile",
  completionPercentage: "Completion Percentage",
  leaderboard: "Leaderboard",
  position: "Rom",
  library: "Library of Context",
  verify: "Mogi",
  nowVerifying: "Icaku mogune..",
  sending: "ti cwalu...",
  sendConfirmation: "Cwal Confirmation",
  startSprint: "Cak Sprint",
  sprintDescription:
    "Sprints ti yub ma ri pi nino abec ka i pimu iye tweru ni mi tic maber. Icani, sprints mira ocake i ceng baraja ki wu tum i ceng abic",
  create: "Yubi",
  pageNoExist: "Tima kija, page ni pe!",
  returnToHome: "Di kany kadok i acaki.",
  markAsComplete: "Di kany ka cwalu ne",
  reviewWork: "Nen tic",
  seeTheProof: "Di kane i nen caden",
  experienceModule: "Experience Module",
  coachDashboard: "MyCoach Athletes",
  pickSprint: "Yer Sprint",
  starts: "Caku",
  finishes: "Agiki",
  close: "loo",
  delete: "Kwanyo",
  weeklyPerformanceAnalytics: "Nen kar itiyu kere i cabit acel acel",
  back: "Angec",
  next: "Cet ayim",
  submitProof: "cwal caden",
  notesForCoach: "Coc mi miyo Coach",
  coachesNotes: "Coc pa Coach",
  submitLink: "Link (GitHub, etc)",
  attachment: "Gin ma nyuru caden",
  messaging: "Pareto League Chat",
  enterMessage: "Iromo Coyo message kany",
  achievements: "Achievements",
  points: "Points",
  viewExperience: "View Progress",
  resources: "Resources",
  openLink: "Yap link i tab mukene",
  confirmation: "Confirmation",
  rank: "Rom",
  name: "Nying",
  score: "Score",
  viewProfile: "Nen Profile",
  creating: "Ti Yubu...",
  reviewFor: "Review for",
  description: "Coc ma logu i kumi",
  clickToDownload: "Di kan i Downloading",
  requestRevisions: "Request Revisions",
  confirmAchievement: "Confirm Achievement",
  dailyPoints: "Points mi ninu ducu",
  daily: "Nino Ducu",
  weekly: "Cabit Ducu",
  weeklyPoints: "Weekly Points",
  upcomingMission: "Loc ma ino i nino ducu",
  finishedMissions: "Loc ma ityeku no",
  goodWork: "Tic maber",
  createTemplate: "Cwe templatd mi Sprint",
  editTemplateName: "Lok nying Template",
  startNewSprint: "Cak Sprint manyen",
  editName: "Lok nyingi",
  changePicture: "Lok cal mi Profile",
  cancel: "Ngolo",
  organization: "Organisasion",
  bio: "Public Bio",
  school: "Gan kwan",
  pleaseChooseAnOption: "Akwayi iyer Option",
  projects: "Projects",
  projectName: "Nying Plojec",
  projectIdeas: "Coc ki tam ikom Plojec",
  noIdeasYet:
    "Pud pi coyo tam ni ikom plojec? Tim ber i di bok ma piny ni ka coyo mo.",
  noProjectsYet:
    "Pud pi cagu tiyu ikom plojec? Tim ber i di piny kenyu ka keddu mo.",
  enterNewProjectIdea: "Ibi Coyo tam ma nyen mi Projec",
  save: "Save",
  githubRepository: "GitHub Repository",
  ifNoSprints: "Di link mamalu ni kacaku Sprint ma nyen!",
  viewSprint: "nen ka Sprint tika wot kere",
  myMentees: "My Mentees",
  options: "Options",
  morning: "Kidiku",
  workday: "Ninu tic",
  evening: "Otyeno",
  sabbath: "Cabat",
  weekend: "Tum pa cabit",
  loading: "Loading",
  selectTemplate: "Yer Sprint Template ni",
  selectPlayers: "Yer jo ma ibi pyem kwedgi",
  trashTalkPSA:
    "Man pire pe tek: lok ma tidi. Cwal lok mo matweru talu nyo cubu cwiny jo ma iti pyem kwedgi.",
  viewProof: "Nen caden",
  noProof: "Pud Pi cwalu caden mokiken",
  arenaNav: "Arena",
  learnNav: "cak kwan",
  libraryNav: "Library",
  chatNav: "Bok lok",
  profileNav: "Profile",
  chatroom: "League Chat",
  createEvent: "Yubbi yub",
  eventName: "Nying yub",
  eventDescription: "Event Description",
  eventLink: "Link mi Event",
  eventDate: "Nino Dwe mi Event",
  eventStart: "cake mi Event",
  eventEnd: "tum pa yub",
  eventType: "Event ango",
  dashboard: "The Arena",
  landingText: "Lok pa Danu",
  fullStackDev: "Full Stack Dev",
  localCommunities: "Local Communities & Meetups",
  suggestResources:
    "Gwel kanyi ka cwalu nying gin mokiken ma medu ngec mi lwak wa",
  incubators: "Start-up incubators & Venture Capital Investors",
  startups: "Kamponi maber mati cake acaga ki mati nyiyu lutic",
  localNews: "Local News & Industry Trends",
  fullName: "Nyingi weng",
  streetAddress: "Adrec ka ibedo iye",
  creditCardInfo: "lok ikum Credit Card",
  myMentors: "lupwonye",
  apprenticeship: "Full-Stack Apprenticeship",
  myCareer: "MyCareer",
  // marketing descriptions
  cheatsheets:
    "karatac 14 makakonyi karu peny ni, matikere pacen 20 mi jemi ma mire inge kakaru peng ni ki pacen 80% ma iti yinyu.",
  flashcards:
    "Kad 52, ma konyi ngeyu jemi madwong ikun JavaScript ki API ne madwong.",
  stickers:
    "Workflow stickers, ma konyi maku terminal commands mi Git ma piretek, AWS Amplify ki Bash iyoroyoro.",
  workbooks:
    "Interactive, physical workbook to help you ideate your capstone portfolio project/product, design wireframe mockups, model the information to store in your database, create an architecture diagram, and more.",
  support: "Priority support & first access to new features.",
  lifetime: "Donyi i knowledge Base ki arena pi kaara ma tut",
  purchase: "wil",
  // productivity to-do list
  morningTitle: "Jemi m'tima i kidiku kano loc",
  morningSummary:
    "cak nino ni ki mit matir - co jemi matima tyen ma ariyo, pwony loku maber ki jo ducu ki bene nyudi maa ki pwoc. Cam dek ki bene tim excercise.",
  dailyExcerciseTitle: "Exercise mi jwi ki jwi",
  exerciseSummary:
    "No cawa 1 pud pukaro i nge kaco ni, itweru tiyu ki dakika 20 ka timu excercise ma tek nyo dakika 30 ka timu excercise ma noknok..",
  meditation: "Meditation",
  meditationSummary:
    "I kine akanyu cawa abiru nyo aboru no ityeko cam dek, ibedi peny iling ki wiyi wukut yamu. Timu kumeno kakonyi medu twe tic ni.",
  eveningTitle: "Jemi ma tima otyeno kano loc",
  eveningSummary:
    "Wegi kong tiyu ki jemi mac (mapat ki Kindle E-Ink). Tam ikum jemi mu time i nino man, gin ma itimo maber, jemi ma iromu mete kere, ki bene jemi ma danu wu timu it in. nini pi cawa maromu 8, daki iromu. matidi loyo iromu nino pi cawa 7.",
  consistencyTitle: "Consistency is King",
  consistencySummary:
    "Yin co nino ki nino i cawa marom, ki i check-in ki app mi Pareto no dakika abic pukaru.",
  deepWork: "cawa 3 mi tic matut",
  deepWorkSummary:
    "Clock in, and clock out. Petye gim mokiken ma twero leyo tic matek. Kadi ni iti caku ne marac, pe wek timu ne, iromu goyo cal nyo yubu ne.",
  eveningCreativity: "Creativity mi Otyeno",
  creativitySummary:
    "Kadi ibi tugo ki jemi mi goyu wer, kwanu buk, coyo buk nyo gin mokiken idyere - tim gi mo madit, nyo ma yabu adam wiyi ki i ywer maber.",
  noSmoking: "Pi mat ta",
  noSmokingSummary:
    "Tiyo ki dopamine kadi pi kara matidi balu twero ni mi tic ma ber. Lubi lok mane no pud pi caku tic ni mi diwo.",
  noDrinking: "Pi Mat Kong i diwo i nino tic",
  noDrinkingSummary:
    "mira imok tam ni ki guvu ni katimu tic maber. Weku matu kong i nino tic ka kony nino maber ki bene medu guvu ni mi timu tic i nino m'ayim",
  eatTheFrog: "Cam ogwal",
  frogSummary:
    "Te coc ni ti ni ityegi tic ma mira itim jwi ki jwi. Jwi ki jwi i bino tic mo ma mira itim ma pire tek tutwal. Ityeku timu ne?",
  secondGoal: "Cam ogwal mukene",
  secondFrogSummary:
    "Tiye gin mo ma ariyo dagi ityeko camu ogwal, Ityeko timu ne?",
  // tours that describe what is going on in the application
  appFirst:
    "Man cake ki camp pwony i Paretto - mati pwony mi internet ma itwero timu tic iye, ki icwalu it lapwonyi ni wu gwer.",
  appSecond:
    'Pareto Arena ti ka itwero pimu iye twe tic ni ki ngeyu ka kwo ni ti wot kede. Loc madit i teknologi mite tic ma tek ma ibi twero lubu pi kara madit. Dagi icagu timu "sprints", iromu neno ka tic ni ki ka kwo ni ti wok kede ikin nino 5. Man konyi ngeyu jemi ma mira itim kanongo loc.',
  appThird: `Library of Context ti ka itwero nongo iye ngec mi pacen 20% ma ka konyi ngeyo pacen 80 ikum jemi ma mite i dibar mi teknoligi, macalu full-stack development. I Library mane, ibi nongo iye jemi maber ma pwonyo ikom React, Node, Amazon Web Services ki jemi mukene ma ka konyi yubu ploglam maber adida.`,
  appFourth:
    "Gin ma wa lwowoni simple Pomodoro ka konyi ngeyu cawa ma itiyo kere katic (Pomodoro) - ki i kara ma ayim, wabi medu jemi mogo iye ma kakonyi ngeyo cawa ma itiyu kere mu wukaru cawa ma mira itir kere.",
  appFifth:
    "Pareto Instant Messenger konyi cwalu mesagi it luremi, mi penyu penyi mogo ki ka bokulok. Wabi medu cwalu mesagi it nyari acel acel i kara mayim.",
  appSixth:
    "Page acel acel ma ti kanyi tiki coc mo ma pwonyi tic kede - Dir ikom cal mi question mark matar ni ma lubu coc mi module ka mete kika ngeyu jemi ma page man twero timu.",
  homeFirst:
    "Ki kanyi, itwero loku nyiyi, cal ni ki lok ma loku ikomi ma danu ka nenu.",
  homeSecond: 'Placeholder',
  homeThird:
    "Ki kany, itwero coyo coc mo ikom plojec ma iti timu. Man medu ngec pa danu ikomi ki benne weku ki lapwony ni ngeyu jemi ma imiru timu i kara m'ayim. Twero bedu tam nyo tic",
  expFirst:
    "Man ti ikin jemi matima i module eni! Itwero diyo nyo gwelu ikome kaneno coc i kuume ma kanyute itung acuc",
  expSecond:
    "Ki bok man, ibi ngeyu jemi ma iti timu, jemu ma ityeko ki jemi ma icwalu ma gwera.",
  expThird:
    'Man nyuru wel EXP ma ibino dagi ityeku timu peny ni - kano romu mi "Advanced Beginner" mira i nong 2000EXP. kabedu "Jr. Developer" mira i nong 6500 EXP. kano roma mi engineer, mira inong 10000EXP ma ti pacen 100 mi completion.',
  expFourth:
    "Man tik maluba dagi imiru tyeko peny ni maber. Ibi no iye coc ma ka konyi ngeyo tyen coyo peny ma iti timu, ki bene piny kenyu ibi no iye coc mo ma ka konyi ngeyu jemi ma mira icawl it lapwony ni.",
  expFifth:
    "Mane ti bok ma idiyo dagi imiru cwalu wak ni. Man it ki apakapoka adek - macel icoyo cocmo it lapwonyi ni ma logu ikom atelatela nyo jemi maber ma ino no ititimu tic ni, ki i kedu iye link mi repository pa github, ci ma agiki, ti iye kamo ka itwero cwalu iye document mo (macalu PDF, screenshot, ki mukene ma patpat.). Tim ber ki pi cwal video mokiken kanyi, ento yabi akawonti mo mi youtube ma ibi cwalu iye video ni ki i kedi link mi vidyo inuni i submission modal.",
  expSixth:
    "Kany tiye modules adek - Onboarding & Training Camp, Building a Product, ki Interviewing me tic cawa weny.",
  libraryFirst:
    "Library wa tiki apokapoka adek, macel ti crowd-sourced Library of Context - ma pwony ikom React, Node.js ki Amazon Web Services i 'Technical Training'. I dul mi 'Finding Work', ibino iye jemi ma ka kony noo tic mapatpat, ki bene kapwonyi nyiyu tic iyuro yuro, ki kacaku kamponi ni ma nyen nyo pwonyi ikom digital nomadism. Bute magiki kilwowoni 'City Guide'. Man nyudi ka itwero no iye kabedo mi teknologi i Citi ma patpat - macalu, joo ma romu kongi caku kamponi ni mayen, Coke, venture capital firms, coding bootcamps ki Kamponi? di ikom bute ma imiru neno ki ibi kwanu jemi mukene ma logu ikume.",
  librarySecond:
    "Man ti ikin dul mapatpat matikere pwony ki jemi mapol mukene mi konyo kwan ni - dagi igwelu, ibi yabu Bute ma tike jami mapol. Ki gwe mo acel ka kwanu coc mo matidi ikume, ci yabi link mane ka nenu coc ni weny. I dul acel acel, iromu coyo gemi ma romu konyu danu mi lwak wa ki ibi no Pareto Credits.",
  libraryThird:
    " Lwak wa dong iyoro ka wan weny wa ribu cing wa. - Di cal eni ka yabu kamo ka iromu cwalu iye jemi ma itamuni twero meddu ngec pa jo mi lwak wa. I kara ma ayim, I bi noo Pareto Credits ma iromu loku kano gemi ma pol. Ngec ti Guvo!",
  arenaFirst:
    "Kanyi nyuru ka Sprint ma ititimu ti wot kwedde- bok mane nyuri Points ma ino i nino ki cabit ducu, ki nyuru bene wel pacen mi ityeku(Completion Percent) i sprint ni. Ki, dagi Sprint ni wotum, ki kwanu pacen mi Completion ma ino ki kiribu ki mi career - mane nyuru jo mu kwon i lwak ni nyo gurup mi luremi.",
  arenaSecond:
    "eni ti ikin jemi ma atima tin - iromu kwanu cik ma aluba, dagi ityeko timu ne ki iwinyo iyube muromu - cwal caden ma nyurnyuru ni ityeko timu tic ni! Itwero cwalu selfie, file mi audio - nyo iromu neno dagi wutum i honor system. Ento nge ni, gemi weng ma icwalu bedu ki cawa ma icwalu kedde - ki dagi idonyu kany no dakika apaa wukaru ki ichawa ma jwi icho kere, no puka kwane ki bene luweddi me pareto league ki koc ni gi bungiyo.",
  arenaThird: "Jwi ki Jwi, ibi no jemi ma ityeku timu piny kenyu.",
  arenaFourth:
    "Di link eni ka caku Sprint mi cabit ma lubo eni! Ento nge ni mira I caki no Ceng Cabit pu karu.",
}