/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:fbb72b0d-bb9c-4625-a05d-9d7465c9b21e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ForfecYcp",
    "aws_user_pools_web_client_id": "57a0fafljaptl6kdent3nog7lq",
    "oauth": {},
    "aws_user_files_s3_bucket": "proofs181835-prod",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://3k2pwcduhrgqlk6c7kocic7gbu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
