/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "us-east-2",
  "aws_cognito_identity_pool_id": "us-east-2:aa99da3b-00a7-4aa2-acf0-9c941aeb2d47",
  "aws_cognito_region": "us-east-2",
  "aws_user_pools_id": "us-east-2_u1790mCly",
  "aws_user_pools_web_client_id": "7lih626j79ejbofng8ldelcq0n",
  "oauth": {},
  "aws_cognito_username_attributes": [
      "EMAIL"
  ],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
      "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OPTIONAL",
  "aws_cognito_mfa_types": [
      "SMS"
  ],
  "aws_cognito_password_protection_settings": {
      "passwordPolicyMinLength": 8,
      "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
      "EMAIL"
  ],
  "aws_cloud_logic_custom": [
      {
          "name": "AdminQueries",
          "endpoint": "https://klegqtbb53.execute-api.us-east-2.amazonaws.com/staging",
          "region": "us-east-2"
      }
  ]
};


export default awsmobile;
